version: "3.6"

services:
  backend:
    image: "php:8.1-rc-apache"
    environment:
      - WORKDIR=/var/www/html
      - EXPOSE=80
    volumes:
      - ./www:/var/www/html/:cached
    ports:
      - 1101:80
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y --no-install-recommends curl unzip netcat libxml2-dev libpq-dev &&
      docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql &&
      docker-php-ext-install pdo pdo_pgsql &&
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&
      source /etc/apache2/envvars &&
      apache2 -D FOREGROUND
      "
  db:
    image: "postgres:11"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
